---

- name: Create {{ stage_name }} Delivery Folder
  win_file:
    path: "{{ delivery_folder }}"
    state: directory

- name: Set Delivery Folder Permissions for {{ stage_user }}
  win_acl:
    path: "{{ delivery_folder }}"
    user: "{{ stage_user }}"
    type: deny
    rights: Write, Delete, DeleteSubdirectoriesAndFiles
    state: present

- name: Share {{ stage_name }} Delivery Folder
  win_share:
    name: "{{ stage_name }} Delivery"
    description: Folder for local delivery of assets for {{ stage_name }}
    path: "{{ delivery_folder }}"
    full: "Everyone"
    state: present