---

- name: Create delivery folder
  win_file:
    path: "{{ delivery_folder }}"
    state: directory

# still need to figure out how to scope down persmissions to avoid adding/deleting files to delivery folder
- name: Set delivery folder to be read only for local user
  win_acl:
    path: "{{ delivery_folder }}"
    user: "{{ project_user }}"
    type: allow
    rights: Read
    state: present

# - name: Explicitly deny write permissions for local user
#   win_acl:
#     path: "{{ delivery_folder }}"
#     user: "{{ project_user }}"
#     type: deny
#     rights: Write
#     state: present

# - name: Explicitly deny modify permissions for local user
#   win_acl:
#     path: "{{ delivery_folder }}"
#     user: "{{ project_user }}"
#     type: deny
#     rights: Modify
#     state: present

- name: Share delivery folder
  win_share:
    name: "{{ share_name }} Delivery"
    description: Folder for local delivery of assets
    path: "{{ delivery_folder }}"
    full: "{{ ansible_user }}"
    state: present