---

- name: Install Chrome
  ansible.windows.win_package:
    path: "https://dl.google.com/chrome/install/latest/chrome_installer.exe"

- name: Install NotchLC
  win_package:
    path: "https://cloudreleases.notch.one/NotchLC_AdobePlugin/NotchLC_AdobeCC_Plugin_1.3.1_win64.exe"
    state: present
    arguments:
      /S

- name: Install Alley
  win_package:
    path: "https://dd5sgwxv3xok.cloudfront.net/Resolume_Alley_7_23_2_rev_51094_Installer.exe"
    state: present
    arguments:
      - /VERYSILENT

- name: Copy FreeFileSync installer to temp
  win_copy:
    src: "FreeFileSync_14.5_[Donation_Edition]_Windows.zip"
    dest: "C:/Windows/Temp/FreeFileSync_14.5_Windows.zip"

- name: Extract FreeFileSync installer
  community.windows.win_unzip:
    src: "C:/Windows/Temp/FreeFileSync_14.5_Windows.zip"
    dest: "C:/Windows/Temp/FreeFileSync"
    creates: "C:/Windows/Temp/FreeFileSync/FreeFileSync_14.5_Windows_Setup.exe"

- name: Install FreeFileSync
  win_package:
    path: "C:/Windows/Temp/FreeFileSync/FreeFileSync_14.5_Windows_Setup.exe"
    arguments: "/S"
    state: present

- name: Remove FreeFileSync temp files
  win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - "C:/Windows/Temp/FreeFileSync_14.5_Windows.zip"
    - "C:/Windows/Temp/FreeFileSync"