--- 

- name: Remove any existing M drive mapping
  win_mapped_drive:
    letter: M
    state: absent

- name: Map Stages Stock Content Drive
  block:
    - name: Save the network credentials
      win_credential:
        name: "{{ hostvars['workstation_1']['ansible_host'] }}"
        # name: 192.168.30.191
        type: domain_password
        username: stages
        secret: stages2025!
        state: present

    - name: Map Stages Stock Content Drive
      win_mapped_drive:
        letter: M
        path: "\\\\{{ hostvars['workstation_1']['ansible_host'] }}\\SS25 Stages Stock Content"
        # path: "\\\\192.168.30.191\\SS25 Stages Stock Content"
        state: present

  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ stage_user }}'
    ansible_become_pass: '{{ stage_password }}'