---

- name: Disable Ethernet 2
  win_shell: |
    Disable-NetAdapter -Name 'Ethernet 2' -Confirm:$false

- name: Rename Ethernet 2
  win_shell: |
    Rename-NetAdapter -Name 'Ethernet 2' -NewName '1G'