# - name: Install Chrome
#   ansible.windows.win_package:
#     path: "https://dl.google.com/chrome/install/latest/chrome_installer.exe"
#     state: present
# - name: Install Wireshark
#   ansible.windows.win_package:
#     path: "https://2.na.dl.wireshark.org/win64/Wireshark-4.4.9-x64.exe"
#     state: present
#     arguments:
#       - /S
#       - /desktopicon=yes
