---

- hosts: all




    ######## Working example of configuring an IP address (can use the commands from Awakening config to finish this)
    # - name: Configure IP
      # win_shell: |
        # Disable-NetAdapter -Name 'Ethernet 2' -Confirm:$false