---

- hosts: all
  roles:
    - base

- hosts: media_servers
  roles:
    - media_servers

- hosts: stage_machines
  roles:
    - stage_machines
    - render_nodes

- hosts: workstations
  roles:
    - workstations
    - render_manager