---
- hosts: all
  roles:
    - base

- hosts: content_machines
  roles:
    - role: content_machines
      content_machines_skip_drive_mapping: true
    - role: render_nodes

- hosts: workstations
  roles:
    - role: workstations
      workstations_skip_drive_mapping: true
    - role: render_manager

- hosts: content_machines
  tasks:
    - name: Map network drives on stage machines
      include_role:
        name: content_machines
        tasks_from: map_network_drives.yml

- hosts: workstations
  tasks:
    - name: Map network drives on workstations
      include_role:
        name: workstations
        tasks_from: map_network_drives.yml