---

# Phase 1: Base setup and share creation (no drive mapping)
- hosts: all
  roles:
    - base

- hosts: media_servers
  roles:
    - media_servers

- hosts: stage_machines
  roles:
    - role: stage_machines
      stage_machines_skip_drive_mapping: true
    # - render_nodes

- hosts: workstations
  roles:
    - role: workstations
      workstations_skip_drive_mapping: true
    # - render_manager

# Phase 2: Map network drives (shares now exist)
- hosts: stage_machines
  tasks:
    - name: Map network drives on stage machines
      include_role:
        name: stage_machines
        tasks_from: map_network_drives.yml

- hosts: workstations
  tasks:
    - name: Map network drives on workstations
      include_role:
        name: workstations
        tasks_from: map_network_drives.yml