---

- name: Download Deadline installer ZIP
  win_get_url:
    url: https://thinkbox-installers.s3.us-west-2.amazonaws.com/Releases/Deadline/10.4/8_10.4.2.2/Deadline-10.4.2.2-windows-installers.zip
    dest: C:\Users\Public\Downloads\Deadline-10.4.2.2-windows-installers.zip

- name: Extract Deadline installer ZIP
  win_unzip:
    src: C:\Users\Public\Downloads\Deadline-10.4.2.2-windows-installers.zip
    dest: C:\Users\Public\Downloads\Deadline
    creates: C:\Users\Public\Downloads\Deadline\Deadline-10.4.2.2-windows-installers

- name: Find Deadline Client installer
  win_find:
    paths: C:\Users\Public\Downloads\Deadline
    patterns: ['*Client*.exe']
    file_type: file
  register: deadline_client_installer

- name: Install Deadline Client
  win_package:
    path: "{{ deadline_client_installer.files[0].path }}"
    state: present
    arguments:
      --mode unattended
      --connectiontype Remote
      --proxyrootdir {{ hostvars['workstation_1']['ansible_host'] }}:8080
      --slavestartup truead

  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ stage_user }}'
    ansible_become_pass: '{{ stage_password }}'